### ISSUE TITLE
SQM: unnecessary dependencies for iptables-mod-filter and iptables-mod-conntrack-extra ?

### ISSUE THREAD

**Issue by hnyman** [dtaht/ceropackages-3.10#13] opened 2015-04-18 08:24 UTC
I noticed unnecessary layer7 files on my router and started investigating bit. It looks like both qos-scripts and sqm-scripts included those files unnecessarily. Openwrt bug: https://dev.openwrt.org/ticket/19506

Nbd has already fixed iptables and qos-scripts (and indirectly also sqm, as those files were removed from iptables), but I think that SQM may still have unnecessary dependencies: for iptables-mod-filter and possibly also for iptables-mod-conntrack-extra.

Those dependencies originate from the original import of qos-scripts to cerowrt as the basis for the new "aqm-scripts", current SQM:  https://github.com/dtaht/ceropackages-3.10/commit/bc8363c4d9795aa90b9acc635ce75f15300c2782

iptables-mod-filter (and kmod-ipt-filter) currently define only packet content string matching. The filter package also pulls in kmod-lib-textsearch, adding to the size. To my knowledge, the string matching is not used in SQM.
https://dev.openwrt.org/browser/trunk/package/network/utils/iptables/Makefile#L117
https://dev.openwrt.org/browser/trunk/package/kernel/linux/modules/netfilter.mk#L163
https://dev.openwrt.org/browser/trunk/include/netfilter.mk#L101

Similarly, iptables-mod-conntrack-extra defines "Matches: - connbytes, - connlimit, - connmark, - recent, - helper" and "Targets - CONNMARK". I don't think that they are used in SQM. (CONNMARK is used by qos, so it is needed there)
https://dev.openwrt.org/browser/trunk/package/network/utils/iptables/Makefile#L97
https://dev.openwrt.org/browser/trunk/package/kernel/linux/modules/netfilter.mk#L142
https://dev.openwrt.org/browser/trunk/include/netfilter.mk#L80

dcsp, tos are defined in "iptables-mod-ipopt", while MARK target is in core iptables.
https://dev.openwrt.org/browser/trunk/include/netfilter.mk#L106
https://dev.openwrt.org/browser/trunk/include/netfilter.mk#L61

So, I don't see a need for iptables-mod-filter and iptables-mod-conntrack-extra in SQM. Or at least the need for them is not immediately visible in the source. I haven't yet tested very deeply, but removing the iptables-mod-filter from my current build did not cause any problems.

I am no netfilter/iptables expert, but though to highlight the possible bloat to the devs.

@moeller0 @tohojo

**Comment by moeller0** [comment] 2015-04-18 09:41
Hi Hnyman,

thanks for the thorough research, from my vintage point this is/was caused by my negligence to actually look into our makefile. (As I am still not setup to actually build cero/openWrt I have no way testing it anyways so I decided to handle this the alleged way of the ostrich by putting my head into the sand). We never have used L7 filtering (and at least I do not plan to go there, DPI even at the home is a loosing proposition in my eyes unless one spends time to keep the filter signatures current, which the L7 packet does/did not as far as I can tell; also I do not see how L7 filtering can work with encrypted packets�
	CONNMARK is something I always wanted to look into, basically to remark incoming packets the same as outbound packets of the same flow. But since ingress handling via IFB does not allow to use iptables this will not work so one more dependency to drop�

Best Regards & many thanks
	Sebastian Moeller

**Comment by moeller0** [comment] 2015-04-19 10:52
Hi Hnyman,

as a first step I removed iptables-mod-filter as we do not use it nor plan to use it in the future.
Let me mull over iptables-mod-conntrack-extra a bit while waiting for reports that the first removal 
does not cause any issues (it should not, but since I am not set up to actually build sqm-scripts
as a package I opt for better safe than sorry).

Best Regards & many thanks for your help and research
	moeller0

**Comment by tohojo** [comment] 2015-04-19 12:20
Merged the patch into the openwrt repo :)

**Comment by moeller0** [comment] 2015-04-19 16:53
Hi Toke,


On Apr 19, 2015, at 14:20 , Toke H�iland-J�rgensen <notifications@github.com> wrote:

> Merged the patch into the openwrt repo :)

Mange Tak.

Best Regards
	Sebastian

**Closed** 2015-08-13 22:52 UTC
